<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TMG-Framework.Test\TMG-Framework.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="XTMF2">
      <HintPath>..\..\..\XTMF2-Dev\XTMF2.dll</HintPath>
    </Reference>
    <Reference Include="XTMF2.Interfaces">
      <HintPath>..\..\..\XTMF2-Dev\XTMF2.Interfaces.dll</HintPath>
    </Reference>   
  </ItemGroup>

</Project>
