<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net10.0</TargetFramework>    
    <RootNamespace>TMG.Test</RootNamespace>    
    <ApplicationIcon />    
    <OutputTypeEx>library</OutputTypeEx>    
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\XTMF2\src\XTMF2.Interfaces\XTMF2.Interfaces.csproj" />
    <ProjectReference Include="..\..\..\XTMF2\src\XTMF2\XTMF2.csproj" />
    <ProjectReference Include="..\..\src\TMG-Framework\TMG-Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
