<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TMG</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>University of Toronto</Authors>
    <Company>University of Toronto</Company>
    <Description>A set of modules for XTMF2 to provide assistance in Travel Demand Modelling.</Description>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\..\XTMF2-Dev\Modules\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="XTMF2">
      <HintPath>..\..\..\XTMF2-Dev\XTMF2.dll</HintPath>
    </Reference>
    <Reference Include="XTMF2.Interfaces">
      <HintPath>..\..\..\XTMF2-Dev\XTMF2.Interfaces.dll</HintPath>
    </Reference>   
  </ItemGroup>

</Project>
