name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2025   
    steps:
    - name: Setup .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.101
    - uses: actions/checkout@v1
      with:
        repository: TravelModellingGroup/XTMF2
        ref: origin/dev
    - name: Build XTMF2  
      run: |
        cd "D:\a\TMG-Framework\XTMF2"
        dotnet build -c Release
    - uses: actions/checkout@v1    
    - name: Build TMG-Framework
      run: |
        cd "D:\a\TMG-Framework\TMG-Framework"
        dotnet build -c Release
    - name: Unit Tests
      run: |
        cd "D:\a\TMG-Framework\TMG-Framework"
        dotnet test -c Release
      
