name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019   
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: |
        cd TMG-Framework
        dotnet build --configuration Release
    - name: Unit Tests
      run: |
        cd TMG-Framework
        dotnet test
      
